### PR TITLE
Fix issue in ZmqSubscriber that can cause a segfault

### PR DESCRIPTION
**Pull request by eflumerf**

### CODE REVIEW

**Review by dingp — COMMENTED** [review]
Found an interesting post about different ways of returning empty string.

https://stackoverflow.com/questions/26587110/returning-an-empty-string-efficient-way-in-c

Looks like `return {}` might be better.

**Comment by eflumerf** [comment]
Interesting, if almost certainly a micro-optimization in this case, since ZmqSubscriber::connect_for_sends should only be called 1/s in the worst case where the other end of the connection is never published to the Connectivity Service

**Review by dingp — APPROVED** [review]
LGTM

**Comment by bieryAtFnal** [comment]
My tests have all run fine so far, but I haven't yet been able to find where the code that calls `connect_for_receives()` checks whether the returned string is empty...

**Comment by eflumerf** [comment]
It doesn't, at the moment (it would be in NetworkManager::create_receiver). While debugging this without the change in `iomanager`, there was an exception raised from that code when it tried to decode the empty string as a ZMQ connection string and failed...

**Comment by dingp** [comment]
Going to merge this PR, and create a new tag to be used for the third candidate release for `v4.1.0` (`rc-v4.1.0-3` and `fd-v4.1.0-c3`).

**Pull request merged**
