### PR TITLE
Lowercase schema names

### PR DESCRIPTION
**Pull request by philiprodrigues**
Change schema names to lower case

### CODE REVIEW

**Comment by eflumerf** [comment]
Do you think we can also remove the -job.jsonnet files?

**Comment by philiprodrigues** [comment]
I was thinking to not remove them until we replace them with python configs. Although maybe they already don't work any more?

**Review by eflumerf — APPROVED** [review]

**Comment by eflumerf** [comment]
I've opened #29 for the -job.jsonnet and approved this PR

**Comment by bieryAtFnal** [comment]
Given that this PR looks to be ready-to-be-merged, I'm going to go ahead and do that, just to move things along a little bit.

**Pull request merged**
