### PR TITLE
Eflumerf/zmq pub sub

### PR DESCRIPTION
**Pull request by eflumerf**
This branch does a number of things:

- Updates the Publisher and Subscriber interfaces
- Renames ipmSender and ipmReceiver to be simply Sender and Receiver
- Adds ZmqPublisher and ZmqSubscriber implementations
- Adds more unit tests
- Changes Sender/Receiver/Publisher/Subscriber to use the duneIPM cetlib plugin type
- Updates VectorIntIPM{Sender,Receiver,Publisher,Subscriber}DAQModule to use correct plugin types

I have not yet run codegen for configuration structs for the new DAQModules. I have also not done any testing beyond the included unit tests. We need to create updated json files for the new format and execute tests using the restcmd library. It would probably be useful for people to include a semi-interactive script which demonstrates the VectorInt example in several different topologies.

### CODE REVIEW

**Comment by jcfreeman2** [comment]
@eflumerf @philiprodrigues I've taken a look at the Publisher and Subscriber interface classes. One thing I'm reflecting on is a consequence of Publisher inheriting from Sender and Subscriber inheriting from Receiver. To focus on Publisher for now, this interface, along with providing users the `publish` and `publish_multipart` functions also provides users the `send` and `send_multipart` functions from the Sender base class, and also needs to implement Sender's protected `send_` function. Currently, we have the following:
```
inline void
Publisher::send_(const void* message, size_type message_size, const duration_type& timeout)
{
  publish_(message, message_size, timeout, "IPM");
}
```
i.e., if you call `send`, you're publishing something with an automatic "IPM" topic. Is "IPM" meant to be a universal topic, and if so, perhaps we could define that formally in the Publisher class? Or do we want users to ever be able to call the topic-less `send` function at all, i.e., do we want users to be able to work polymorphically with a Publisher in the context of it being a Sender? If not, we could consider scrapping Publisher's inheritance from Sender, and instead use Sender and Receiver exclusively to build the many-to-many, request/reply communication object I understand we want along with a publisher and a subscriber.

**Comment by eflumerf** [comment]
These are good points, and the choice of "IPM" was entirely arbitrary (Maybe "" would be better, as I think it would then go to all subscribers regardless of their subscriptions, but I'm not sure about the exact ZMQ implementation there). I was trying to avoid a #define and I don't think that strings can be constexpr...if you have a better way to do it, by all means make that change.

If you look at ZmqPublisher_test, I am explicitly testing that it can be constructed as a Sender handle, and I used the same plugin types for all of the IPM classes "duneIPM". The plugin loading code first makes a Sender/Receiver, then sees if it can do a dynamic_cast to Publisher/Subscriber. We could, of course, have the code construct handles to Publisher/Subscriber explicitly and have implementations of the form

```
class DoEverythingIPM : public Sender, Receiver, Publisher, Subscriber
...
DEFINE_DUNE_IPM_RECEIVER(DoEverythingIPM)
DEFINE_DUNE_IPM_SENDER(DoEverythingIPM)
...
```

**Comment by jcfreeman2** [comment]
@eflumerf Interesting point about `#define`s and `constexpr`s, I'll think about how to go about this. And concerning the plugin approach, you know more about plugins than I do, but from my perspective it sounds like your approach is fine. 

I've been reflecting (more) on the Publisher and Subscriber interfaces. I see that a lot of the logic concerning error checking, multiple message sending, etc. was essentially cut-and-pasted from Sender into Publisher (e.g., compare `Sender::send_multipart` and `Publisher::publish_multipart`). It seems like this is necessary because `Sender::send_` doesn't contain a provision for the concept of a topic. What are your thoughts on having `Sender::send_` take an optional argument meant to be metadata about the blob of bytes being sent (looping @philiprodrigues in as well at this point)? It could be a `std::string`, an `nlohmann::json` object or something else. If we did this, the Publisher interface could be very simple, since it could use that metadata argument for topics. The Publisher could just inherit from Sender, and then perhaps have an additional `publish` function where the topic argument was mandatory, passing it on to the `send_` function. 

As far as Subscriber goes, it seems like again a lot of the cut-and-pasting could be simplified if we added an optional metadata (topic) argument to `Receiver::receive`. It would still be a bit more complex than the Publisher since it would retain the `subscribe` and `unsubscribe` functions, but implementors of the Subscriber interface could just confer the meaning of "topic" to the optional third argument. 

Thoughts?

**Comment by philiprodrigues** [comment]
If the topic stuff is the only difference between `Publisher` and `Sender`, I wonder if, in the interests of keeping things simple to begin with, we should just leave it out, and have every subscribe socket just subscribe to all messages. I can't think of places in the DAQ where a publisher would be producing multiple different "types" of message, so that subscribers would want to filter them out (but maybe I just haven't thought hard enough).

**Comment by eflumerf** [comment]
The ZeroMQ socket type is also different ("pub" vs. "push"), but we could make that configurable...

**Comment by jcfreeman2** [comment]
Great. If we remove topics from the publisher, we can always add them back in if there's a demand for them without breaking anyone's code. And as far as configurability goes, we could just have an enum as an argument to the constructor of the implementation of `Sender` which defines how the sending would work.

**Comment by eflumerf** [comment]
OK, I've talked with John about this, and I've made another commit which greatly simplifies the Subscriber interface and removes the Publisher interface completely. ZmqSender/ZmqPublisher and ZmqReceiver/ZmqSubscriber are now both thin wrappers around ZmqSenderImpl and ZmqReceiverImpl with different Zmq socket types used in the constructor (decided by an enum parameter to Zmq...Impl's constructor).

**Pull request merged**
